// <auto-generated />
using Airport;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace Airport.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Airport.PlaneType", b =>
                {
                    b.Property<int>("PlaneTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("PlaneTypeId");

                    b.ToTable("PlaneTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
